### ISSUE TITLE
Cannot login for export with MacPro 3,1 / C4D R20 / OSX 10.11.4 or iMacPro as well

### ISSUE THREAD

**Issue by sbgraphic** [sketchfab/c4d-plugin#10]
Hello,

I’ve noticed the following issue with this release:
https://github.com/sketchfab/c4d-plugin/releases/tag/1.3.0

Configuration:
OSX 10.11.4  /  MacPro 3,1  /  C4D R20

I cannot login to my account…
I can monitor there is a internet connection to your website but nothing append…

Same issue on this another configuration:
OSX 10.14.6  /  iMacPro  /  C4DR20 or C4DR21 

Best,
Eric

**Comment by PadreZippo** [comment]
Hello,

Can you go to "**Script → Console → Python**", try to log in, and share any error message?

**Comment by sbgraphic** [comment]
Hello, good news, I've tried the same way with R20 today on MacPro 10.11.4 and it worked... 
The result was as expected. 

```
Latest Sketchfab plugin version is 1.3.0
FBX export successful.
```
Sorry for the trouble !

**Comment by imashination** [comment]
Same problem here. If I try to login on the exporter page first, nothing happens. I need to login on the importer, close that and then login with the exporter page for it to work

C4D 20.059
win 10
plugin v 1.3.0
other plugins: octane v4.07, xparticles 4

**Comment by loicSketchfab** [comment]
Hello @imashination and thanks for the info.

The latest release was not tested for R20, but should hopefully fix this problem.

Could you give it a go with the version 1.3.1 of the plugin, available here : https://github.com/sketchfab/c4d-plugin/releases/tag/1.3.1 ?

**Comment by imashination** [comment]
1.3.1 fixes the login issue on R20, thanks :)
