### ISSUE TITLE
Does not load in R22 for Mac

### ISSUE THREAD

**Issue by ckfishh** [sketchfab/c4d-plugin#12]

**Comment by MarcusMorba** [comment]
Same for me, tried several options and path, but none worked.

**Comment by loicSketchfab** [comment]
Hello @ckfishh and @MarcusMorba, and thanks for your feedbacks.

There were some API changes between R21 and S22, and we've updated the plugin for C4D S22.

Could you please try to use the version 1.3.1 of the plugin, available here ?
https://github.com/sketchfab/c4d-plugin/releases/tag/1.3.1

**Comment by ckfishh** [comment]
Thank you, @loicSketchfab that is working for me! I had to fight with the security settings of OSX for the plugin to load, like other similar plugins, but it's importing and working well now. Thanks!

**Comment by MarcusMorba** [comment]
Thanks a lot!
