### ISSUE TITLE
Suddenly cannot access my own models C4D r22?

### ISSUE THREAD

**Issue by kobocha** [sketchfab/c4d-plugin#16]
Hi!

I've been using the sketchfab plugin now for weeks and it's performed perfectly. Now a couple of days ago I noticed that I cannot download my own models anymore. Not happens when I click them. This is not an issue with the other models, like the staff picks for example. They all work perfectly. 

I've tried reinstalling cinema, tried an older version of cinema. As well as on a different computer. It's the same issue. Might it have something to do with my Sketchfab account?

Ps. As mentioned in the title I'm using C4D r22 and I'm on sketchfab 1.3.1.

Cheers,
Lewis

**Comment by PadreZippo** [comment]
Hi Lewis,

Hmm. What’s your Sketchfab username?

James

**Comment by kobocha** [comment]
> Hi Lewis,
> 
> Hmm. What’s your Sketchfab username?
> 
> James

Hi James!

The username is mattias@whereismypony.se

Br,
L

**Comment by PadreZippo** [comment]
Got it, thanks!

Looks like you only have one model right?

We recently improved the security of accessing password-protected models via the Data API. I think this is related. Does downloading “my own models” work in the plug-in if you make this model private (instead of password-protected), or if you upload another model?

**Comment by kobocha** [comment]
Correct. My colleague is the one uploading. We found this workaround since he works in blender and I work in C4D. Where do I change it from password protected to private? Do you mean to set it as "anyone who has the link"? 

Gonna try to upload another model and see if that works. I'll report back soon! 

Ps. For the private setting to trigger, do I need to re-upload or should the settings kick in automatically?  

Br,
L

**Comment by PadreZippo** [comment]
Yes, you can change the privacy in Model Properties. The change happens immediately.

![image](https://user-images.githubusercontent.com/7097291/98152260-6d75c480-1e9f-11eb-90e7-30117af4184c.png)

**Comment by kobocha** [comment]
> Yes, you can change the privacy in Model Properties. The change happens immediately.
> 
> ![image](https://user-images.githubusercontent.com/7097291/98152260-6d75c480-1e9f-11eb-90e7-30117af4184c.png)

Excellent PadreZippo! This seems to have solved the issue. I just hope that the client is ok with the models being hidden instead of password protected. But I'm guessing its basically as secure?

Thanks for the excellent support my man!

Have a great day and thanks for the quick response!

Br,
L

**Comment by PadreZippo** [comment]
Great! Hopefully in the future we can update our importer plugins to handle the new authentication measures on password-protected models.

Yes, as long as you don't share the model's URL, it's just as secure when "private".

Feel free to delete your email address from your previous message (as this repo is public). Dropping your profile URL here for posterity: https://sketchfab.com/whereismypony

**Comment by kobocha** [comment]
Great idea! Can we instead link my private account at sketchfab for posterity instead? https://sketchfab.com/kobocha 

Feel free to also delete this message.

Really appreciate the help I've recieved here. You've done me a huge solid mate!
