### ISSUE TITLE
Does not load in Win R23

### ISSUE THREAD

**Issue by maxjix** [sketchfab/c4d-plugin#17]

**Comment by TIMBLOCKER** [comment]
Same problem, its because R21/S22 Plugins are not compatible with newer C4D versions due to new API architecture.

https://developers.maxon.net/?p=3633 

Please rebuild the plugin to fit the R23 version because this is the only glTF-Import capable plugin...

**Comment by loicSketchfab** [comment]
Hey @TIMBLOCKER @maxjix :wave: 

We've just updated the plugin to support R23.
You can give it a go [here](https://github.com/sketchfab/c4d-plugin/releases/tag/1.4.0).

I'll close this issue for now, but please let us know if something goes wrong while installing/using it, and do not hesitate to re-open the issue if necessary.

**Comment by TIMBLOCKER** [comment]
Hey Loïc,

thanks for messaging me. I’m very happy to try the plugin …

 

Von: Loïc Norgeot [mailto:notifications@github.com] 
Gesendet: Dienstag, 22. Dezember 2020 17:39
An: sketchfab/c4d-plugin <c4d-plugin@noreply.github.com>
Cc: TIMBLOCKER <tim.borkowy@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sketchfab/c4d-plugin] Does not load in Win R23 (#17)

 

Hey @TIMBLOCKER <https://github.com/TIMBLOCKER>  @maxjix <https://github.com/maxjix>  👋

We've just updated the plugin to support R23.
You can give it a go here <https://github.com/sketchfab/c4d-plugin/releases/tag/1.4.0> .

I'll close this issue for now, but please let us know if something goes wrong while installing/using it, and do not hesitate to re-open the issue if necessary.
